### ISSUE TITLE
object "design.mat" not found

### ISSUE THREAD

**Issue by aespin** [SteinCK/M-ComBat#1]
I am using R version 3.2.1 in Ubuntu, with "BiocInstaller_1.18.3" and "sva_3.14.0".
When I try to run the line:

> RES2 <- M.COMBAT( C , batch , center=1 , mod )  # perform  M-ComBat centered at batch 1
> The error message "object "design.mat" not found" appears (refering to the line from the loop "M.COMBAT" in the script: "design <- sva:::design.mat(mod, numCov = numCovs)").
> However, using a previous version from R/sva it does work...is it possible?
> Thanks in advance, 
> Almudena

**Comment by SteinCK** [comment]
You are right. Newer sva package removes some of the functions necessary to run implementation of MComBat.  
I will add additional code that functions with R 3.2.1 and sva 3.14.0
